
.Dd 2024-09-01
.Dt LIBFOO 3
.Os
.Sh NAME
.Nm bar ,
.Nm baz
.Nd foo functions
.Sh LIBRARY
.Lb libfoo
.Sh SYNOPSIS
.In foo.h
.\" Function signatures
.Ft double
.Fn foo "double x"
.Sh DESCRIPTION
The
.Fn bar
and
.Fn baz
functions compute ...
.Sh IMPLEMENTATION NOTES
.Sh RETURN VALUES
The
.Fn bar
and
.Fn baz
functions return ...
.Sh EXAMPLES
.Sh SEE ALSO
.Xr sin 3 ,
.Xr mmap 2
.Sh STANDARDS
.Sh HISTORY
.Sh AUTHORS
.An Roland Smith Aq Mt rsmith@xs4all.nl
.\" EOF
